name: transcribit_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  audioplayers: ^6.1.0
  dio: ^5.7.0
  file_picker: ^8.1.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.3.0
  path: ^1.9.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  record: ^5.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
