# Generated by Django 5.1.2 on 2024-10-22 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('path_file', models.FileField(upload_to='')),
                ('token_url', models.CharField(max_length=255)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('duration', models.TimeField()),
                ('language', models.CharField(max_length=25)),
                ('language_probability', models.FloatField()),
                ('topic', models.CharField(max_length=25)),
                ('tag', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('minutes_start', models.FloatField()),
                ('minutes_end', models.FloatField()),
                ('segment_edit', models.CharField(max_length=255)),
                ('segment_original', models.CharField(max_length=255)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('transcription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='transcription.transcription')),
            ],
        ),
    ]
