# Generated by Django 5.1.2 on 2024-10-26 03:34

import transcription.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='token_url',
            field=models.CharField(default=transcription.models.generate_token, editable=False, max_length=255, unique=True),
        ),
    ]
