# Generated by Django 5.1.2 on 2024-10-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0004_alter_segment_id_alter_state_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='duration',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='language',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='language_probability',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='tag',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='topic',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
