# Generated by Django 5.1.2 on 2024-10-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0005_alter_transcription_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='transcription_id',
            new_name='transcription',
        ),
    ]
