# Generated by Django 5.1.2 on 2024-10-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0006_rename_transcription_id_segment_transcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='segment_edit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
